version: '3'
services:
  redis:
    container_name: sentry-redis
    image: redis:4.0
    restart: always
    network_mode: bridge
  postgres:
    container_name: sentry-postgres
    image: postgres:10.3
    environment:
      - POSTGRES_USER=sentry
      - POSTGRES_PASSWORD=change_it
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    restart: always
    network_mode: bridge
  sentry-cron:
    container_name: sentry-cron
    image: sentry:8.22
    environment:
      - SENTRY_SECRET_KEY=generate_it
      - SENTRY_EMAIL_HOST=change_it
      - SENTRY_EMAIL_PORT=587
      - SENTRY_EMAIL_USER=change_it
      - SENTRY_EMAIL_PASSWORD=change_it
      - SENTRY_SERVER_EMAIL=change_it
      - SENTRY_REDIS_PORT=6379
      - SENTRY_POSTGRES_PORT=5432
    links:
      - redis
      - postgres
    command: sentry run cron
    restart: always
    network_mode: bridge
  sentry-worker:
    container_name: sentry-worker
    image: sentry:8.22
    environment:
      - SENTRY_SECRET_KEY=generate_it
      - SENTRY_EMAIL_HOST=change_it
      - SENTRY_EMAIL_PORT=587
      - SENTRY_EMAIL_USER=change_it
      - SENTRY_EMAIL_PASSWORD=change_it
      - SENTRY_SERVER_EMAIL=change_it
      - SENTRY_REDIS_PORT=6379
      - SENTRY_POSTGRES_PORT=5432
    links:
      - redis
      - postgres
    command: sentry run worker
    restart: always
    network_mode: bridge
  sentry:
    container_name: sentry
    image: sentry:8.22
    environment:
      - VIRTUAL_HOST=change_it
      - LETSENCRYPT_HOST=change_it
      - LETSENCRYPT_EMAIL=change_it
      - SENTRY_SECRET_KEY=generate_it
      - SENTRY_EMAIL_HOST=change_it
      - SENTRY_EMAIL_PORT=587
      - SENTRY_EMAIL_USER=change_it
      - SENTRY_EMAIL_PASSWORD=change_it
      - SENTRY_SERVER_EMAIL=change_it
      - SENTRY_REDIS_PORT=6379
      - SENTRY_POSTGRES_PORT=5432
    links:
      - redis
      - postgres
    restart: always
    network_mode: bridge
