redis:
  image: redis
  restart: always

postgres:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=sentry
    - POSTGRES_USER=your-great-password
  volumes:
    - ./postgresql:/var/lib/postgresql/data
  restart: always

sentry:
  image: sentry
  environment:
    - VIRTUAL_HOST=your.host.tdl
    - LETSENCRYPT_HOST=your.host.tdl
    - LETSENCRYPT_EMAIL=your@letsencrypt.email
    - SENTRY_SECRET_KEY=your-generated-key
    - SENTRY_EMAIL_HOST=your-smtp-host
    - SENTRY_EMAIL_PORT=587
    - SENTRY_EMAIL_USER=your.smtp.username
    - SENTRY_EMAIL_PASSWORD=your-smtp-password
    - SENTRY_SERVER_EMAIL=your.sender.adress
  links:
    - redis
    - postgres
  restart: always

sentry-cron:
  image: sentry
  environment:
    - SENTRY_SECRET_KEY=your-generated-key
    - SENTRY_EMAIL_HOST=your-smtp-host
    - SENTRY_EMAIL_PORT=587
    - SENTRY_EMAIL_USER=your.smtp.username
    - SENTRY_EMAIL_PASSWORD=your-smtp-password
    - SENTRY_SERVER_EMAIL=your.sender.adress
  links:
    - redis
    - postgres
  command: sentry run cron
  restart: always


sentry-worker:
  image: sentry
  environment:
    - SENTRY_SECRET_KEY=your-generated-key
    - SENTRY_EMAIL_HOST=your-smtp-host
    - SENTRY_EMAIL_PORT=587
    - SENTRY_EMAIL_USER=your.smtp.username
    - SENTRY_EMAIL_PASSWORD=your-smtp-password
    - SENTRY_SERVER_EMAIL=your.sender.adress
  links:
    - redis
    - postgres
  command: sentry run worker
  restart: always